<a href="https://colab.research.google.com/github/mascDriver/data-science/blob/main/GEX637_T%C3%B3picos_especiais_em_computa%C3%A7%C3%A3o_XV_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importando bibliotecas e abertura do arquivo

In [1]:
import numpy as np
import math
import pandas as pd
import time
import sys


with open('wi29.tsp') as f:
  content = [line.strip() for line in f.read().splitlines()]
length_tsp = int(content[4].split()[-1].strip())+1
length_tsp

30

### Removendo valores iniciais e EOF do final

In [2]:
content = content[7:]
content = content[:-1]
content[-1]

'29 27462.5000 12992.2222'

## Criação da matriz com o calculo das distancias entre os pontos

In [30]:
array_result = []
dimension = np.ndarray((length_tsp-1, length_tsp-1), dtype=int)
for key_x, x in enumerate(content):
  id_x, x1, y1 = np.array(x.split(), dtype=float)
  for key_y, y in enumerate(content):
    id_y, x2, y2 = np.array(y.split(), dtype=float)
    dimension[key_x][key_y] = round(math.sqrt(math.pow(x1-x2, 2)+math.pow(y1-y2, 2)))
df = pd.DataFrame(dimension, dtype=int)
df

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,0,75,4110,3048,2267,974,4190,3302,4758,3044,...,8009,7398,7266,7425,9639,9229,8320,9301,8102,7799
1,75,0,4070,2999,2214,901,4137,3239,4701,2970,...,7938,7324,7192,7351,9570,9159,8248,9230,8029,7724
2,4110,4070,0,1172,1973,3496,891,1815,1415,3673,...,5595,5726,5810,5857,6675,6465,6060,6522,6164,6163
3,3048,2999,1172,0,817,2350,1172,995,1797,2648,...,5695,5536,5545,5634,7044,6740,6110,6804,6090,5976
4,2267,2214,1973,817,0,1533,1924,1188,2497,2208,...,6094,5754,5711,5827,7572,7220,6471,7288,6373,6186
5,974,901,3496,2350,1533,0,3417,2410,3935,2114,...,7039,6429,6302,6458,8685,8267,7347,8338,7130,6832
6,4190,4137,891,1172,1924,3417,0,1233,651,3086,...,4775,4843,4921,4971,5977,5719,5227,5780,5301,5281
7,3302,3239,1815,995,1188,2410,1233,0,1586,1877,...,4906,4615,4599,4700,6400,6037,5287,6105,5209,5051
8,4758,4701,1415,1797,2497,3935,651,1586,0,3285,...,4180,4356,4468,4497,5330,5083,4645,5143,4761,4787
9,3044,2970,3673,2648,2208,2114,3086,1877,3285,0,...,5217,4421,4256,4428,7000,6513,5455,6587,5156,4801
10,3095,3021,3777,2755,2312,2175,3184,1979,3374,107,...,5221,4401,4227,4402,7016,6523,5450,6597,5140,4776
11,3986,3914,2996,2315,2324,3014,2202,1321,2177,1360,...,4031,3474,3402,3530,5733,5282,4334,5354,4142,3897
12,5093,5024,2876,2720,3088,4141,1987,1900,1576,2674,...,3007,2866,2934,2987,4547,4153,3399,4222,3375,3306
13,6406,6337,3904,3972,4400,5449,3064,3213,2491,3822,...,1725,1998,2212,2172,3238,2831,2164,2901,2284,2397
14,5903,5829,5056,4547,4557,4955,4180,3556,3884,2864,...,2880,1701,1450,1650,4780,4197,2931,4270,2470,2010
15,8436,8368,5441,5802,6341,7490,4734,5175,4088,5889,...,1275,2651,3018,2837,1244,1088,1642,1129,2252,2773
16,6963,6890,4990,4883,5174,5989,4116,4005,3600,4089,...,1173,796,1040,974,3063,2504,1367,2578,1207,1201
17,6694,6620,5150,4886,5071,5724,4261,3946,3818,3722,...,1776,705,663,756,3674,3089,1834,3162,1438,1120
18,6576,6501,5316,4959,5074,5615,4425,3992,4029,3560,...,2174,929,698,885,4064,3468,2177,3540,1698,1252
19,8009,7938,5595,5695,6094,7039,4775,4906,4180,5217,...,0,1400,1770,1577,1900,1331,510,1405,1002,1498
20,7398,7324,5726,5536,5754,6429,4843,4615,4356,4421,...,1400,0,371,198,3222,2610,1285,2679,769,440
21,7266,7192,5810,5545,5711,6302,4921,4599,4468,4256,...,1770,371,0,220,3583,2969,1638,3037,1070,560
22,7425,7351,5857,5634,5827,6458,4971,4700,4497,4428,...,1577,198,220,0,3370,2754,1422,2822,851,374
23,9639,9570,6675,7044,7572,8685,5977,6400,5330,7000,...,1900,3222,3583,3370,0,620,1951,559,2580,3173
24,9229,9159,6465,6740,7220,8267,5719,6037,5083,6513,...,1331,2610,2969,2754,620,0,1333,75,1960,2553
25,8320,8248,6060,6110,6471,7347,5227,5287,4645,5455,...,510,1285,1638,1422,1951,1333,0,1400,648,1230
26,9301,9230,6522,6804,7288,8338,5780,6105,5143,6587,...,1405,2679,3037,2822,559,75,1400,0,2024,2616
27,8102,8029,6164,6090,6373,7130,5301,5209,4761,5156,...,1002,769,1070,851,2580,1960,648,2024,0,593
28,7799,7724,6163,5976,6186,6832,5281,5051,4787,4801,...,1498,440,560,374,3173,2553,1230,2616,593,0

### Verificando qual é a menor distancia a ser percorrida em X tempo

In [7]:
t = time.process_time()
best_tsp = {'time': float('inf'), 'caminho': []}
array_random = np.arange(length_tsp-1)
elapsed_time = 0
while(elapsed_time < 1):
  distancia = 0
  np.random.shuffle(array_random)
  elapsed_time = time.process_time() - t
  for key, position in enumerate(array_random):
    try:
      distancia += dimension[position][array_random[key+1]]
    except:
      distancia += dimension[position][array_random[0]]
  if distancia < best_tsp['time']:
    best_tsp['time'] = distancia
    best_tsp['caminho'] = array_random

best_tsp

{'caminho': array([28, 26, 24,  9, 14,  1, 19, 18, 10, 11, 13,  8, 17,  2,  0, 12, 21,
         4, 16, 27,  5,  7, 20, 22,  3,  6, 23, 15, 25]), 'time': 69150.0}